server:
  port: 8201

spring:
  cloud:
    function:
      definition: consumer;errorSupplier
    stream:
      kafka:
        default:
          consumer:
            autoCommitOffset: false
      bindings:
        consumer-in-0:
          destination: resilience-input
          contentType: application/json
          group: server
        errorSupplier-out-0:
          destination: resilience-output-error
          contentType: application/json

resilience4j:
  circuitbreaker:
    instances:
      insert:
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10
        failureRateThreshold: 25
        waitDurationInOpenState: 10000
        automaticTransitionFromOpenToHalfOpenEnabled: true
        registerHealthIndicator: true

  retry:
    instances:
      insert:
        retryExceptions:
          - java.lang.IllegalArgumentException

management:
  metrics:
    enable:
      all: true
  influx:
    metrics:
      export:
        enabled: true
        step: 10s
        bucket: scst
        token: A4XPNzOdvdbJQudj0th08N-aNH65vdfzLlFS4YlNy9leoUPLzuKUmD7hoNKdieejs9CHd0eFWsM_9IDAmI9GWQ==
        org: vmware

logging.level.org.springframework.cloud.function.context.catalog: WARN
