server:
  port: 8202

spring:
  cloud:
    stream:
      bindings:
        supplier-out-0:
          destination: resilience-input
          contentType: application/json

logging.level.org.springframework.cloud.function.context.catalog: OFF