server:
  port: 8202

spring:
  cloud:
    stream:
      bindings:
        supplier-out-0:
          destination: resilience-input
          contentType: application/json

management:
  metrics:
    enable:
      all: true
  influx:
    metrics:
      export:
        enabled: true
        step: 10s
        bucket: scst
        token: A4XPNzOdvdbJQudj0th08N-aNH65vdfzLlFS4YlNy9leoUPLzuKUmD7hoNKdieejs9CHd0eFWsM_9IDAmI9GWQ==
        org: vmware

logging.level.org.springframework.cloud.function.context.catalog: WARN